#!/usr/bin/env python3
"""
Basic dictionary
"""

BaseCaching = _import_('base_caching').BaseCaching

class BasicCache(BaseCaching):
"""
Basic Cache class tht inherits form the  BaseCaching
"""

def put(self, key, item)
"""
must assign to the dictionaty self.cahe_data the item value for the key key

"""
if key and item:
self.cahe_data[key] = item

def get(self, key):
self.cache_data[key] = item

def get(self, key):
"""
must return the value in self.cache_data linked to key.
""
return self.cache_data.get(key,Non



#iiijiippl[pop[k];
45)
